version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8010:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: azerty11
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: azerty11
      MYSQL_ROOT_PASSWORD: azerty11
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8020:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: azerty11
    depends_on:
      - db
volumes:
  wordpress:
  db:
